# data:
#   build: /Users/bjorn/Dropbox/go/src/github.com/fjukstad/kvik/pipeline/docker/fileserver/
#load-balancer:
#  build: /Users/bjorn/Dropbox/go/src/github.com/fjukstad/kvik/pipeline/docker/load-balancer/
#  ports: 
#    - "80:80"
#    - "8004:8004" 
#  links: 
#    - opencpu
#  expose: 
#    - "80"
#    - "8004"
worker: 
  build: /Users/bjorn/Dropbox/go/src/github.com/fjukstad/kvik/pipeline/docker/worker/
  expose: 
    - "80" 
  volumes:
    - /tmp
  volumes_from:
    - data 
haproxy:
  image: tutum/haproxy
  #build: /Users/bjorn/Dropbox/go/src/github.com/fjukstad/kvik/pipeline/docker/haproxy/
  links:
    - worker
  ports:
    - "80"
    - "1936:1936"
  environment:
    - TIMEOUT=connect 5000, client 500000, server 500000
