name: x-y plot
stages:
- name: x-numbers
  package: stats
  function: rnorm
  arguments:
    n: 100
    mean: 50
    sd: 10

- name: y-numbers
  package: stats
  function: rnorm
  arguments:
    n: 100
    mean: 0
    sd: 10

- name: plot
  package: graphics
  function: plot
  arguments:
    x: from:x-numbers
    y: from:y-numbers
